### ISSUE TITLE
What is the source in this repository?

### ISSUE THREAD

**Issue by KwonTae-young** [hosang89/AndroidStudy#1]
Hi.
What is the source in this repository?

**Comment by hosang89** [comment]
Hi~

**Comment by xoduddk123** [comment]
Please **answer** my question.

**Comment by hosang89** [comment]
This repository is my study space~!!!!!!!!!!!!~!~!~!~!

Press Like Button ~

**Comment by xoduddk123** [comment]
you are troll.

**Comment by hosang89** [comment]
Umm...
I think you'll live in Anyang.

So Press!! Like Button

**Comment by xoduddk123** [comment]
ㅗ

**Comment by hosang89** [comment]
You are 노잼

**Comment by xoduddk123** [comment]
ㅗ

**Comment by hosang89** [comment]
Thank you

**Comment by KwonTae-young** [comment]
OMG......

**Comment by hosang89** [comment]
p{margin-top:0;margin-bottom:0}
    


    Hi!!!!Bye~~
--------- 원본 메일 ---------

    
        보낸사람: Kwon Tae-young <notifications@github.com>
        받는사람: hosang89/AndroidStudy <AndroidStudy@noreply.github.com>
        
            참조: hosang89 <news899@daum.net>, Comment <comment@noreply.github.com>
        
        날짜: 19.01.31 17:27 GMT +0900
        제목: Re: [hosang89/AndroidStudy] What is the source in this repository? (#1)
        
        
    
    
        Closed #1.
